### PR TITLE
feat: integrating armadillo in tests

### PR DESCRIPTION
**Pull request by sidohaakma**

### CODE REVIEW

**Comment by ymarcon** [comment]
Not sure it is a good idea to replace the reference implementation (OpalDriver) with the Armadillo one. Your code should offer the possibility to switch to Armadillo easily instead (same thing for DSLite).

**Comment by StuartWheater** [comment]
Sido, if I create an alternative branch, say "armadillo-integration", could you direct the pull request to that branch?

**Comment by sidohaakma** [comment]
> Not sure it is a good idea to replace the reference implementation (OpalDriver) with the Armadillo one. Your code should offer the possibility to switch to Armadillo easily instead (same thing for DSLite).

Hi Yannick, that was definitely not the idea. This PR is only a reference for Stuart to get a basic idea of how things work. The code is based on the first local test to get the dsBaseClient unit tests to work. ;-D. Sorry that I gave you the impression that I refactored Opal out of the datasets initialisation ;-P.

**Comment by sidohaakma** [comment]
> Sido, if I create an alternative branch, say "armadillo-integration", could you direct the pull request to that branch?

Yes, done!

**Comment by StuartWheater** [comment]
I will close this PR. I have created another PR with your R script and some of your test changes, I will work on the others test changes so they will work with both Opal and Armadillo.
Stuart

**Pull request closed without merging**
