### PR TITLE
new version of isDefined

### PR DESCRIPTION
**Pull request by davraam**
we need to update the tests to reflect the additional argument and the updated format of the error message.

### CODE REVIEW

**Comment by davraam** [comment]
we can also add these tests in the CI:

# Example 1: Cheeck if the dataframe D exists in all studies
isDefined(datasources=connections, obj="D")

# Example 2: Check if the object D$LAB_HDL exists in all studies
isDefined(datasources=connections, obj="D$LAB_HDL")

# Example 3: Check if the object hdl_exp exists in all studies
ds.exp("D$LAB_HDL", newobj = "hdl_exp", datasources=connections[c(1,3)])
isDefined(datasources=connections, obj="hdl_exp")
ds.dataFrame(c("D","hdl_exp"), newobj = "D2", datasources=connections[c(1,3)])
isDefined(datasources=connections, obj="D2")

# Example 4: Check if the object hdl_log exists in all studies
ds.log("D$LAB_HDL", newobj = "hdl_log", datasources=connections[c(2)])
isDefined(datasources=connections, obj="hdl_log")
isDefined(datasources=connections, obj="hdl_log", error.message = FALSE)

**Comment by StuartWheater** [comment]
Is master branch your intended target branch?

**Comment by davraam** [comment]
> Is master branch your intended target branch?

No, should be 6.2-dev. Can we change that?

**Comment by StuartWheater** [comment]
Easiest to close this Pull Request, and create a new PR.

**Comment by davraam** [comment]
> Easiest to close this Pull Request, and create a new PR.

OK, let's do that

**Pull request closed without merging**
