### PR TITLE
Phase 1: changes for levelsDS

### PR DESCRIPTION
**Pull request by StuartWheater**
Also includes a typo fix

### CODE REVIEW

**Comment by OllyButters** [comment]
Your man files are out of date.

**Comment by OllyButters** [comment]
I reluctantly agree that I am being a little harsh on the CI halting for this. I'll turn it down a notch.

**Comment by StuartWheater** [comment]
I would leave the test, best if every test we can think of needs to be passed.

**Comment by OllyButters** [comment]
I mean that perhaps the CI shouldn't stop if this test doesn't pass. It *has* to be fixed before the code is merged, but maybe it's useful for the PR owner to see *all* of their errors not just the first one? What do you think?

**Comment by StuartWheater** [comment]
I agree, stopping the CI process isn't desirable, but not accepting changed, generally, the right ideas. 
(But this is phase one won't fix all the problem, phase 2 coming)

**Comment by OllyButters** [comment]
Merging - but only on the promise that a subsequent PR is going to fix the new errors!

**Pull request merged**
