### PR TITLE
To v6.0 dev

### PR DESCRIPTION
**Pull request by tombisho**
I think my previous pull request was mistakenly asking to pull into dsBaseClient/master, when it should have been dsBaseClient/v6.0-dev. I hope this attempt looks a bit more sensible.

### CODE REVIEW

**Comment by OllyButters** [comment]
That does look much better!

**Comment by OllyButters** [comment]
It is failing its build though. It looks like there is a reference to one of @StuartWheater repos that doesn't exist any more:
https://github.com/tombisho/dsBaseClient/blob/f6d44a40e211869dbb6ca2b57221680c74e3f130/azure-pipelines.yml#L56

presumably this should point to:

https://github.com/datashield/datashield-infrastructure/tree/v6.0-dev

Or are there outstanding changes to be merged in first?

**Comment by tombisho** [comment]
I think it's because I forgot to change the server IP address back to 127.0.0.1 after setting it to 192.168.56.100

What's the best way forward, do I need to fix it in my repo and reissue the PR?

**Comment by OllyButters** [comment]
You can carry on committing to this and it magically appears in the same PR.

The line in the azure-pipelines.yml does need fixing too.

**Comment by tombisho** [comment]
Ok that was not what I had in mind. I haven't finished fixing the azure bit yet. Should I revert the merge?

**Comment by OllyButters** [comment]
Ha! I didn't realise you had the permission to do that. Might revoke that... No need to revert, just put in a new PR with the rest of the fixes.

**Comment by tombisho** [comment]
No I didn't expect that to happen either. Can I leave it to you to revoke it?

**Comment by OllyButters** [comment]
As it happens I had already made the same fix to the azure-pipelines.yml file for a different commit earlier today, this being newer than your edits means that it is all fixed now. I have manually triggered a CI build to check, but I think we can relax now.

I was hesitant to revert the merge as this has interesting behaviour later on when you try to merge in the same files again.

**Comment by tombisho** [comment]
ok great. It looks like there is now a branch called revert114 (or similar) which you might need to tidy up. Apologies for messing things up!

**Comment by OllyButters** [comment]
Don't worry about it - I've done it several times myself!

**Pull request merged**
