### PR TITLE
updates based on the addition of colnamesDS, dimDS, lengthDS

### PR DESCRIPTION
**Pull request by davraam**

### CODE REVIEW

**Comment by OllyButters** [comment]
@StuartWheater @davraam 

There is a merge conflict in this PR. Can you let me know which bit of code I should keep and I will fix it before merging?

https://github.com/datashield/dsBaseClient/pull/161/conflicts

**Comment by davraam** [comment]
We should keep line 110 and delete line 112

**Comment by StuartWheater** [comment]
I think the line:

l <- DSI::datashield.aggregate(datasources[i], call('lengthDS', x))[[1]]

Should be kept.

**Comment by OllyButters** [comment]
This has produced >100 new errors in the CI. Can you run devtools::test() locally and fix the issues you see locally then recommit. Also the man files need updating. You can see the output of the CI in the link above, or at:

https://dev.azure.com/datashield-testing/datashield/_build/results?buildId=97&view=logs&j=67f900c1-8873-56e2-c3e2-bdaf0e5a579f

Cheers,

Olly

**Comment by StuartWheater** [comment]
I think a new version of dsBase is needed including 'colnamesDS.R'
(colnamesDS also added to DESCRIPTION file, and devtools::document() to
update NAMESPACE).

**Comment by OllyButters** [comment]
I've merged in the dsBase PR to v6.0-dev, but this PR is still causing a lot of errors:

https://dev.azure.com/datashield-testing/datashield/_build/results?buildId=107&view=logs&j=2c943ca1-d502-523e-32c1-a57511339818&t=db6a9c6a-107c-5299-d735-c7ee79321ef8

Is devtools::test() running ok locally @davraam ?

**Comment by davraam** [comment]
most of the failures are related to the replacment of paste0() with call() & eval() combination. I will investigate this.

**Comment by OllyButters** [comment]
There is now a merge conflict with this PR. Can you let me know what should be kept - @davraam @StuartWheater

**Comment by davraam** [comment]
Since Stuart added eval(parse(…)) on the server-side, the line 140 should be kept.

**Comment by OllyButters** [comment]
Having rerun the tests on the code after fixing the merge conflict there are 129 errors/failures across 20 different contexts:

https://dev.azure.com/datashield-testing/datashield/_build/results?buildId=130&view=logs&j=67f900c1-8873-56e2-c3e2-bdaf0e5a579f&t=cb858b11-febd-5f4d-8c52-00f7d26ddec1

I don't think this PR will have all the changes made over the last few days since the PR was opened. Unless either @StuartWheater or @davraam have a better idea of what is going on I suggest either:

rebase your code (i.e. pull in all the changes that have happened since you checked out this version) or create a new fork from v6.0-dev and copy your edited files into that.

**Comment by OllyButters** [comment]
Hi @davraam - there is a conflict with this that needs to be fixed, and it is still throwing 100s errors. 

I actually don't think you'll get this PR to work as so much has changed in the branch. I would strongly recommend you close this PR, create a new fork of v6.0-dev, copy your new code into that, then open a new PR.

**Comment by davraam** [comment]
i agree. I am going to close this PR.

**Pull request closed without merging**
