### PR TITLE
V6.0 dev testing

### PR DESCRIPTION
**Pull request by LeireAbarrategui**

### CODE REVIEW

**Comment by OllyButters** [comment]
Hi @LeireAbarrategui 

the CI reports 100s of errors, see:

https://dev.azure.com/datashield-testing/datashield/_build/results?buildId=108&view=logs&j=2c943ca1-d502-523e-32c1-a57511339818&t=db6a9c6a-107c-5299-d735-c7ee79321ef8

Does devtools::test() run successfully on your laptop?

**Comment by LeireAbarrategui** [comment]
Yes, devtools::test() run successfully on my computer.

**Comment by StuartWheater** [comment]
The problem is caused by you tests using dsDangerClient functions. The neither dsDanger or dsDangerClient are deployed to the CI system.

**Comment by OllyButters** [comment]
@LeireAbarrategui - as mentioned this morning the thing to do is to take a copy of your changes elsewhere, and redo this dev without the danger functions. As such I am going to close this PR without merging it in.

**Pull request closed without merging**
