### PR TITLE
Added boxplot

### PR DESCRIPTION
**Pull request by ESCRI11**
Client functions for the boxplot with ggplot

### CODE REVIEW

**Comment by ymarcon** [comment]
Same comment as for the server side package: ggplot2 dependency should be added in the DESCRIPTION file.

**Comment by StuartWheater** [comment]
It appears I need to add the installations of 'ggplot2' and 'gridExtra' packages the CI.

**Comment by ymarcon** [comment]
@StuartWheater Why the dsBaseClient dependencies are not getting installed automatically ?

**Comment by ESCRI11** [comment]
Whenever you find some free time to install the additional R packages please make sure to also install the ones needed for the dsBase check. Let me know when it's ready and I will re-launch the testing. Thanks!

**Comment by StuartWheater** [comment]
Pull request about to be sent to you for dsBase and dsBaseClient, just finishing testing...

**Pull request merged**
